import { StyleSheet } from "react-native";

export const ContactStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#1f1f1f",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  headerTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    flex: 1,
    textAlign: "center",
  },
  headerSubTitle: {
    color: "#aaa",
    fontSize: 14,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#1f1f1f",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  searchIconLeft: {
    marginRight: 10,
  },
  searchIconRight: {
    marginLeft: 10,
  },
  searchInput: {
    flex: 1,
    color: "#fff",
    fontSize: 16,
    paddingVertical: 5,
  },
  headerButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
    backgroundColor: "#1f1f1f",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  headerButtonText: {
    color: "#aaa",
    fontSize: 16,
  },
  tabActive: {
    color: "#007AFF",
    fontWeight: "bold",
  },
  menuContainer: {
    padding: 10,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    backgroundColor: "#1f1f1f",
    borderRadius: 10,
    marginBottom: 10,
  },
  menuIcon: {
    backgroundColor: "#007AFF",
    borderRadius: 15,
    padding: 5,
    marginRight: 10,
    marginLeft: 10,
  },
  menuText: {
    color: "#fff",
    fontSize: 16,
  },
  menuSubText: {
    color: "#aaa",
    fontSize: 14,
    marginLeft: 10,
  },
  contactListContainer: {
    flex: 1,
  },
  tabSwitchContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
    backgroundColor: "#1f1f1f",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  tabItem: {
    paddingHorizontal: 10,
  },
  tabText: {
    color: "#aaa",
    fontSize: 16,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 15,
  },
  contactName: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  contactPhone: {
    color: "#aaa",
    fontSize: 14,
  },
  alphabetList: {
    position: "absolute",
    right: 5,
    top: 50,
    bottom: 50,
    justifyContent: "space-around",
  },
  alphabetText: {
    color: "#007AFF",
    fontSize: 12,
  },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: "#1f1f1f",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  groupHeaderText: {
    color: "#fff",
    fontSize: 16,
  },
  tabSwitchContainerGroup: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: "#1f1f1f",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  filterButton: {
    padding: 5,
  },
  groupItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  groupMessage: {
    color: "#aaa",
    fontSize: 14,
  },
  groupTime: {
    color: "#aaa",
    fontSize: 12,
  },
  oaItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  // Style cho giao diện "Thêm bạn"
  qrContainer: {
    alignItems: "center",
    padding: 20,
  },
  qrCode: {
    width: 200,
    height: 200,
    backgroundColor: "#007AFF",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  qrPlaceholder: {
    color: "#fff",
    fontSize: 16,
  },
  qrDescription: {
    color: "#fff",
    fontSize: 14,
    marginVertical: 10,
  },
  phoneInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1f1f1f",
    borderRadius: 5,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  phoneCode: {
    color: "#fff",
    fontSize: 16,
    marginRight: 10,
  },
  phoneInput: {
    flex: 1,
    color: "#fff",
    fontSize: 16,
    paddingVertical: 10,
  },
  arrowButton: {
    padding: 5,
  },
  optionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  optionText: {
    color: "#fff",
    fontSize: 16,
    marginLeft: 10,
  },
  noteText: {
    color: "#aaa",
    fontSize: 12,
    textAlign: "center",
    marginTop: 10,
  },
  // Style cho giao diện "Sinh nhật"
  sectionTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  birthdayItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  birthdayText: {
    color: "#aaa",
    fontSize: 14,
  },
  chatButton: {
    padding: 5,
  },
  noDataText: {
    color: "#aaa",
    fontSize: 16,
    textAlign: "center",
    marginTop: 20,
  },
  // Style cho giao diện "Tạo nhóm"
  groupNameContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: "#1f1f1f",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  groupNameInput: {
    flex: 1,
    color: "#fff",
    fontSize: 16,
    marginLeft: 10,
  },
  friendItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  selectedFriendsContainer: {
    padding: 10,
    backgroundColor: "#1f1f1f",
    borderTopWidth: 1,
    borderTopColor: "#333",
  },
  selectedFriendItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 5,
    marginBottom: 5,
  },
  selectedAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 10,
  },
  selectedName: {
    color: "#fff",
    fontSize: 14,
    flex: 1,
  },
  createGroupButton: {
    backgroundColor: "#007AFF",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
  createGroupText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  qrUserName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    marginBottom: 10,
  },
});